# Generated by Django 4.1.4 on 2022-12-27 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profiledetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.profiledetails'),
        ),
    ]
