# Generated by Django 4.1.4 on 2022-12-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_profiledetails_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiledetails',
            name='detail',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='profiledetails',
            name='medical_field',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profiledetails',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile.png', null=True, upload_to=''),
        ),
    ]
